export type {
    Item,
    Message,
    ModalSetting,
    Photo,
    Search,
    dialogSetting,
    statusAction,
    statusButton,
    statusDialog,
    statusForm,
    statusIcon,
    variantButton
} from './common.types';
export type {
    CustomButtonIconProps,
    CustomButtonProps,
    CustomCategoryFormProps, CustomDetailsCategoryProps,
    CustomDetailsProductProps,
    CustomDialogProps,
    CustomHeaderProps,
    CustomHeaderUserProps,
    CustomInputProps,
    CustomItemProps,
    CustomItemTabsProps,
    CustomLaboratoryFormProps,
    CustomListProps,
    CustomLoadingProps,
    CustomMessageErrorProps,
    CustomModalProps,
    CustomPhotoProps,
    CustomProductFormProps,
    CustomProgressBarProps,
    CustomSearchFormProps,
    CustomSelectProps,
    CustomTabsProps,
    CustomTextAreaProps, CustomViewDisabledProps, IconProps,
    PosterProps
} from './component.types';

